title: Lokesh Jaliminche
description: PhD Student Computer Science, University of California Santa Cruz

google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
